/*
 * Copyright (c) 2014-present, salesforce.com, inc.
 * All rights reserved.
 * Redistribution and use of this software in source and binary forms, with or
 * without modification, are permitted provided that the following conditions
 * are met:
 * - Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * - Neither the name of salesforce.com, inc. nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission of salesforce.com, inc.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.salesforce.androidsdk.util

import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

/**
 * This allows other classes (primarily test classes) to register & receive events generated by the sdk.
 */
object JSONObjectHelper {

    /**
     * Return null if object doesn't have key or if obj has null for key
     * JSONObject.opt(key) return the JSONObject.NULL if object has null for key and null if object doesn't have key
     */
    @JvmStatic
    fun opt(obj: JSONObject, key: String): Any? {
        return if (obj.isNull(key)) null else obj.opt(key)
    }

    /**
     * Return null if arr doesn't have value at index or the value is null
     * JSONArray.opt(index) return the JSONObject.NULL if array has null at index and null if array doesn't have value at index
     */
    @JvmStatic
    fun opt(arr: JSONArray, index: Int): Any? {
        return if (arr.isNull(index)) null else arr.opt(index)
    }

    /**
     * Return null if obj doesn't have key or if obj has null for key - and return value as a  String[] otherwise
     *
     * @param obj
     * @param key
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun optStringArray(obj: JSONObject, key: String): Array<String>? {
        var result: Array<String>? = null
        val jsonArray = if (obj.isNull(key)) null else obj.getJSONArray(key)
        if (jsonArray != null) {
            result = Array(jsonArray.length()) { i ->
                jsonArray.getString(i)
            }
        }
        return result
    }

    /**
     * Return null if obj doesn't have key or if obj has null for key
     * JSONObject.optString(key, fallback) returns the string "null" if object has null for key and null if object doesn't have key
     *
     * @param obj
     * @param key
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun optString(obj: JSONObject, key: String): String? {
        return optString(obj, key, null)
    }

    /**
     * Return the fallback if obj doesn't have key or if obj has null for key
     * JSONObject.optString(key, fallback) returns the string "null" if object has null for key and null is object doesn't have key
     *
     * @param obj
     * @param key
     * @param fallback
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun optString(obj: JSONObject, key: String, fallback: String?): String? {
        return if (obj.isNull(key)) fallback else obj.getString(key)
    }

    /**
     * Convert JSONArray of T into list of T
     * @param jsonArray
     * @param T
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun <T> toList(jsonArray: JSONArray?): List<T> {
        if (jsonArray == null) {
            return emptyList()
        }
        val arr = mutableListOf<T>()
        for (i in 0 until jsonArray.length()) {
            @Suppress("UNCHECKED_CAST")
            arr.add(jsonArray.get(i) as T)
        }
        return arr
    }

    /**
     * Convert JSONObject into Map of String to T
     * @param jsonObject
     * @param T
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun <T> toMap(jsonObject: JSONObject?): Map<String, T> {
        if (jsonObject == null) {
            return emptyMap()
        }
        val map = mutableMapOf<String, T>()
        val it = jsonObject.keys()
        while (it.hasNext()) {
            val key = it.next()
            @Suppress("UNCHECKED_CAST")
            map[key] = jsonObject.get(key) as T
        }
        return map
    }

    /**
     * Given a JSONArray of JSONObject, return list made of values for key
     * @param jsonArray
     * @param key
     * @param T
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun <T> pluck(jsonArray: JSONArray, key: String): List<T> {
        val arr = mutableListOf<T>()
        for (i in 0 until jsonArray.length()) {
            @Suppress("UNCHECKED_CAST")
            arr.add(jsonArray.getJSONObject(i).get(key) as T)
        }
        return arr
    }

    /**
     * Given an array of JSONObject, return list made of values for key
     * @param jsonObjects
     * @param key
     * @param T
     * @return
     * @throws JSONException
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun <T> pluck(jsonObjects: Array<JSONObject>, key: String): List<T> {
        val arr = mutableListOf<T>()
        for (jsonObject in jsonObjects) {
            @Suppress("UNCHECKED_CAST")
            arr.add(jsonObject.get(key) as T)
        }
        return arr
    }

    /**
     *
     * @param key
     * @param value
     * @return JSONObject with value for key
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun makeJSONObject(key: String, value: Any): JSONObject {
        val result = JSONObject()
        result.put(key, value)
        return result
    }

    /**
     * Add all elements from array to destinationArray
     *
     * @param destinationArray
     * @param array
     */
    @JvmStatic
    @Throws(JSONException::class)
    fun addAll(destinationArray: JSONArray, array: JSONArray) {
        for (i in 0 until array.length()) {
            destinationArray.put(array.getJSONObject(i))
        }
    }
}
