package com.salesforce.androidsdk.mobilesync.config
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.SmallTest
import com.salesforce.androidsdk.mobilesync.app.MobileSyncSDKManager
import com.salesforce.androidsdk.mobilesync.manager.SyncManagerTestCase
import com.salesforce.androidsdk.mobilesync.target.*
import com.salesforce.androidsdk.mobilesync.util.*
import com.salesforce.androidsdk.mobilesync.util.SyncState.MergeMode
import org.junit.After
import org.junit.Assert
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class) @SmallTest
class SyncsConfigTest : SyncManagerTestCase() {
    @Before override fun setUp() { super.setUp() }
    @After override fun tearDown() { super.tearDown() }

    @Test fun testSetupGlobalSyncsFromDefaultConfig() { Assert.assertFalse(globalSyncManager.hasSyncWithName("globalSync1")); Assert.assertFalse(globalSyncManager.hasSyncWithName("globalSync2")); MobileSyncSDKManager.getInstance().setupGlobalSyncsFromDefaultConfig(); Assert.assertTrue(globalSyncManager.hasSyncWithName("globalSync1")); Assert.assertTrue(globalSyncManager.hasSyncWithName("globalSync2")); val actualSync1 = globalSyncManager.getSyncStatus("globalSync1")!!; Assert.assertEquals("Wrong soup name", ACCOUNTS_SOUP, actualSync1.soupName); checkStatus(actualSync1, SyncState.Type.syncDown, actualSync1.id, SoqlSyncDownTarget("SELECT Id, Name, LastModifiedDate FROM Account"), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0); val actualSync2 = globalSyncManager.getSyncStatus("globalSync2")!!; Assert.assertEquals("Wrong soup name", ACCOUNTS_SOUP, actualSync2.soupName); checkStatus(actualSync2, SyncState.Type.syncUp, actualSync2.id, CollectionSyncUpTarget(listOf("Name"), null), SyncOptions.optionsForSyncUp(listOf("Id", "Name", "LastModifiedDate"), MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
    @Test fun testSetupUserSyncsFromDefaultConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); Assert.assertTrue(syncManager.hasSyncWithName("soqlSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("soslSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("mruSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("refreshSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("layoutSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("metadataSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("parentChildrenSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("briefcaseSyncDown")); Assert.assertTrue(syncManager.hasSyncWithName("singleRecordSyncUp")); Assert.assertTrue(syncManager.hasSyncWithName("batchSyncUp")); Assert.assertTrue(syncManager.hasSyncWithName("collectionSyncUp")); Assert.assertTrue(syncManager.hasSyncWithName("parentChildrenSyncUp")) }
    @Test fun testSoqlSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("soqlSyncDown")!!; Assert.assertEquals("Wrong soup name", ACCOUNTS_SOUP, sync.soupName); checkStatus(sync, SyncState.Type.syncDown, sync.id, SoqlSyncDownTarget(null, null, "SELECT Id, Name, LastModifiedDate FROM Account"), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testSoqlSyncDownWithBatchSizeFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("soqlSyncDownWithBatchSize")!!; Assert.assertEquals("Wrong soup name", ACCOUNTS_SOUP, sync.soupName); checkStatus(sync, SyncState.Type.syncDown, sync.id, SoqlSyncDownTarget(null, null, "SELECT Id, Name, LastModifiedDate FROM Account", 200), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testSoslSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("soslSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, SoslSyncDownTarget("FIND {Joe} IN NAME FIELDS RETURNING Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
    @Test fun testMruSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("mruSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, MruSyncDownTarget(listOf("Name", "Description"), "Account"), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testRefreshSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("refreshSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, RefreshSyncDownTarget(listOf("Name", "Description"), "Account", "accounts"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
    @Test fun testLayoutSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("layoutSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, LayoutSyncDownTarget("Account", "Medium", "Compact", "Edit", null), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testMetadataSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("metadataSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, MetadataSyncDownTarget("Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
    @Test fun testParentChildrenSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("parentChildrenSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, ParentChildrenSyncDownTarget(ParentInfo("Account", "accounts", "IdX", "LastModifiedDateX"), listOf("IdX", "Name", "Description"), "NameX like 'James%'", ChildrenInfo("Contact", "Contacts", "contacts", "AccountId", "IdY", "LastModifiedDateY"), listOf("LastName", "AccountId"), ParentChildrenSyncTargetHelper.RelationshipType.MASTER_DETAIL), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testBriefcaseSyncDownFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("briefcaseSyncDown")!!; checkStatus(sync, SyncState.Type.syncDown, sync.id, BriefcaseSyncDownTarget(listOf(BriefcaseObjectInfo("accounts", "Account", listOf("Name", "Description")), BriefcaseObjectInfo("contacts", "Contact", listOf("FirstName"), "IdX", "LastModifiedDateX"))), SyncOptions.optionsForSyncDown(MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testSingleRecordSyncUpFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("singleRecordSyncUp")!!; checkStatus(sync, SyncState.Type.syncUp, sync.id, SyncUpTarget(listOf("Name"), listOf("Description")), SyncOptions.optionsForSyncUp(listOf(), MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
    @Test fun testBatchSyncUpFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("batchSyncUp")!!; checkStatus(sync, SyncState.Type.syncUp, sync.id, BatchSyncUpTarget(null, null, "IdX", "LastModifiedDateX", "ExternalIdX", BatchSyncUpTarget.MAX_SUB_REQUESTS_COMPOSITE_API), SyncOptions.optionsForSyncUp(listOf("Name", "Description"), MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testCollectionSyncUpFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("collectionSyncUp")!!; checkStatus(sync, SyncState.Type.syncUp, sync.id, CollectionSyncUpTarget(null, null, "IdX", "LastModifiedDateX", "ExternalIdX", CollectionSyncUpTarget.MAX_RECORDS_SOBJECT_COLLECTION_API), SyncOptions.optionsForSyncUp(listOf("Name", "Description"), MergeMode.OVERWRITE), SyncState.Status.NEW, 0) }
    @Test fun testParentChildrenSyncUpFromConfig() { MobileSyncSDKManager.getInstance().setupUserSyncsFromDefaultConfig(); val sync = syncManager.getSyncStatus("parentChildrenSyncUp")!!; checkStatus(sync, SyncState.Type.syncUp, sync.id, ParentChildrenSyncUpTarget(ParentInfo("Account", "accounts", "IdX", "LastModifiedDateX", "ExternalIdX"), listOf("IdX", "Name", "Description"), listOf("Name", "Description"), ChildrenInfo("Contact", "Contacts", "contacts", "AccountId", "IdY", "LastModifiedDateY", "ExternalIdY"), listOf("LastName", "AccountId"), listOf("FirstName", "AccountId"), ParentChildrenSyncTargetHelper.RelationshipType.MASTER_DETAIL), SyncOptions.optionsForSyncUp(listOf(), MergeMode.LEAVE_IF_CHANGED), SyncState.Status.NEW, 0) }
}
