package com.salesforce.androidsdk.mobilesync.manager

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.filters.LargeTest
import com.salesforce.androidsdk.mobilesync.target.*
import com.salesforce.androidsdk.mobilesync.util.*
import com.salesforce.androidsdk.mobilesync.util.SyncState.MergeMode
import com.salesforce.androidsdk.mobilesync.util.SyncState.Status.*
import com.salesforce.androidsdk.mobilesync.util.SyncState.Type.syncDown
import com.salesforce.androidsdk.smartstore.store.QuerySpec
import org.json.JSONArray
import org.json.JSONObject
import org.junit.After
import org.junit.Assert
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.util.Arrays
import java.util.Collections.singletonList

@RunWith(AndroidJUnit4::class) @LargeTest
class SyncManagerTest : SyncManagerTestCase() {
    companion object { protected const val COUNT_TEST_ACCOUNTS = 10; val REFRESH_FIELDLIST = listOf(Constants.ID, Constants.NAME, Constants.DESCRIPTION, Constants.LAST_MODIFIED_DATE) }
    protected lateinit var idToFields: MutableMap<String, Map<String, Any>>

    @Before override fun setUp() { super.setUp(); createAccountsSoup(); idToFields = createRecordsOnServerReturnFields(COUNT_TEST_ACCOUNTS, Constants.ACCOUNT, null) }
    @After override fun tearDown() { if (::idToFields.isInitialized) { deleteRecordsByIdOnServer(idToFields.keys, Constants.ACCOUNT) }; dropAccountsSoup(); super.tearDown() }

    @Test fun testGetSyncStatusForInvalidSyncId() { val sync = syncManager.getSyncStatus(-1); Assert.assertNull("Sync status should be null", sync) }
    @Test fun testSyncDown() { trySyncDown(MergeMode.OVERWRITE); checkDb(idToFields, ACCOUNTS_SOUP) }
    @Test fun testSyncDownWithoutOverwrite() { trySyncDown(MergeMode.OVERWRITE); val idToFieldsLocallyUpdated = makeLocalChanges(idToFields, ACCOUNTS_SOUP); trySyncDown(MergeMode.LEAVE_IF_CHANGED); val idToFieldsExpected = HashMap(idToFields); idToFieldsExpected.putAll(idToFieldsLocallyUpdated); checkDb(idToFieldsExpected, ACCOUNTS_SOUP); trySyncDown(MergeMode.OVERWRITE); checkDb(idToFields, ACCOUNTS_SOUP) }
    @Test fun testSyncDownForMetadataTarget() { trySyncDown(MergeMode.LEAVE_IF_CHANGED, MetadataSyncDownTarget(Constants.ACCOUNT), ACCOUNTS_SOUP); val smartStoreQuery = QuerySpec.buildAllQuerySpec(ACCOUNTS_SOUP, SyncTarget.SYNC_ID, QuerySpec.Order.ascending, 1); val rows = smartStore.query(smartStoreQuery, 0); Assert.assertEquals("Number of rows should be 1", 1, rows.length()); val metadata = rows.optJSONObject(0); Assert.assertNotNull("Metadata should not be null", metadata); Assert.assertEquals("Key prefix should be 001", Constants.ACCOUNT_KEY_PREFIX, metadata!!.optString(Constants.KEYPREFIX_FIELD)); Assert.assertEquals("Label should be Account", Constants.ACCOUNT, metadata.optString(Constants.LABEL_FIELD)) }
    @Test fun testSyncDownForLayoutTarget() { trySyncDown(MergeMode.LEAVE_IF_CHANGED, LayoutSyncDownTarget(Constants.ACCOUNT, Constants.FORM_FACTOR_MEDIUM, Constants.LAYOUT_TYPE_COMPACT, Constants.MODE_EDIT, null), ACCOUNTS_SOUP); val smartStoreQuery = QuerySpec.buildAllQuerySpec(ACCOUNTS_SOUP, SyncTarget.SYNC_ID, QuerySpec.Order.ascending, 1); val rows = smartStore.query(smartStoreQuery, 0); Assert.assertEquals("Number of rows should be 1", 1, rows.length()); val layout = rows.optJSONObject(0); Assert.assertNotNull("Layout should not be null", layout); Assert.assertEquals("Layout type should be Compact", Constants.LAYOUT_TYPE_COMPACT, layout!!.optString(LayoutSyncDownTarget.LAYOUT_TYPE)); Assert.assertEquals("Mode should be Edit", Constants.MODE_EDIT, layout.optString(LayoutSyncDownTarget.MODE)) }
    @Test fun testReSync() { val syncId = trySyncDown(MergeMode.OVERWRITE); val sync = syncManager.getSyncStatus(syncId)!!; val target = sync.target as SyncDownTarget; val options = sync.options; val maxTimeStamp = sync.maxTimeStamp; Assert.assertTrue("Wrong time stamp", maxTimeStamp > 0); val idToFieldsUpdated = makeRemoteChanges(idToFields, Constants.ACCOUNT); val queue = SyncUpdateCallbackQueue(syncId); syncManager.reSync(syncId, queue); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, RUNNING, 0, -1); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, RUNNING, 0, idToFieldsUpdated.size); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, DONE, 100, idToFieldsUpdated.size); checkDb(idToFieldsUpdated, ACCOUNTS_SOUP); Assert.assertTrue("Wrong time stamp", syncManager.getSyncStatus(syncId)!!.maxTimeStamp > maxTimeStamp) }
    @Test fun testReSyncByName() { val syncName = "syncForTestReSyncByName"; val syncId = trySyncDown(MergeMode.OVERWRITE, syncName); val sync = syncManager.getSyncStatus(syncId)!!; val target = sync.target as SyncDownTarget; val options = sync.options; val maxTimeStamp = sync.maxTimeStamp; Assert.assertTrue("Wrong time stamp", maxTimeStamp > 0); val idToFieldsUpdated = makeRemoteChanges(idToFields, Constants.ACCOUNT); val queue = SyncUpdateCallbackQueue(syncId); syncManager.reSync(syncName, queue); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, RUNNING, 0, -1); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, RUNNING, 0, idToFieldsUpdated.size); checkStatus(queue.getNextSyncUpdate(syncId), syncDown, syncId, target, options, DONE, 100, idToFieldsUpdated.size); checkDb(idToFieldsUpdated, ACCOUNTS_SOUP); Assert.assertTrue("Wrong time stamp", syncManager.getSyncStatus(syncId)!!.maxTimeStamp > maxTimeStamp) }
    @Test fun testReSyncByNameWithWrongName() { try { syncManager.reSync("testReSyncByNameWithWrongName", null); Assert.fail("Expected exception") } catch (e: SyncManager.MobileSyncException) { Assert.assertTrue(e.message!!.contains("does not exist")) } }
    @Test fun testCustomSyncUpWithLocallyUpdatedRecords() { trySyncDown(MergeMode.OVERWRITE); val idToFieldsLocallyUpdated = makeLocalChanges(idToFields, ACCOUNTS_SOUP); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.NO_FAIL); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); checkDbStateFlags(idToFieldsLocallyUpdated.keys, false, false, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records updated by target", 3, collector.updatedRecordIds.size); for (id in collector.updatedRecordIds) { Assert.assertTrue("Unexpected id:$id", idToFieldsLocallyUpdated.containsKey(id)) } }
    @Test fun testCustomSyncUpWithLocallyCreatedRecords() { val names = arrayOf(createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT)); createAccountsLocally(names); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.NO_FAIL); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); val idToFieldsCreated = getIdToFieldsByName(ACCOUNTS_SOUP, arrayOf(Constants.NAME, Constants.DESCRIPTION), Constants.NAME, names); checkDbStateFlags(idToFieldsCreated.keys, false, false, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records created by target", 3, collector.createdRecordIds.size); for (id in collector.createdRecordIds) { Assert.assertTrue("Unexpected id:$id", idToFieldsCreated.containsKey(id)) }; idToFields.putAll(idToFieldsCreated) }
    @Test fun testCustomSyncUpWithLocallyDeletedRecords() { trySyncDown(MergeMode.OVERWRITE); val allIds = idToFields.keys.toTypedArray(); val idsLocallyDeleted = arrayOf(allIds[0], allIds[1], allIds[2]); deleteRecordsLocally(ACCOUNTS_SOUP, *idsLocallyDeleted); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.NO_FAIL); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); checkDbDeleted(ACCOUNTS_SOUP, idsLocallyDeleted, Constants.ID); Assert.assertEquals("Wrong number of records created by target", 3, collector.deletedRecordIds.size); for (id in idsLocallyDeleted) { Assert.assertTrue("Id not synched up$id", collector.deletedRecordIds.contains(id)) } }
    @Test fun testSoftFailingCustomSyncUpWithLocallyUpdatedRecords() { trySyncDown(MergeMode.OVERWRITE); val idToFieldsLocallyUpdated = makeLocalChanges(idToFields, ACCOUNTS_SOUP); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.SOFT_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); checkDbStateFlags(idToFieldsLocallyUpdated.keys, false, true, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records updated by target", 0, collector.updatedRecordIds.size) }
    @Test fun testHardFailingCustomSyncUpWithLocallyUpdatedRecords() { trySyncDown(MergeMode.OVERWRITE); val idToFieldsLocallyUpdated = makeLocalChanges(idToFields, ACCOUNTS_SOUP); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.HARD_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE, true); checkDbStateFlags(idToFieldsLocallyUpdated.keys, false, true, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records updated by target", 0, collector.updatedRecordIds.size) }
    @Test fun testSoftFailingCustomSyncUpWithLocallyCreatedRecords() { val names = arrayOf(createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT)); createAccountsLocally(names); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.SOFT_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); val idToFieldsCreated = getIdToFieldsByName(ACCOUNTS_SOUP, arrayOf(Constants.NAME, Constants.DESCRIPTION), Constants.NAME, names); checkDbStateFlags(idToFieldsCreated.keys, true, false, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records created by target", 0, collector.createdRecordIds.size); idToFields.putAll(idToFieldsCreated) }
    @Test fun testHardFailingCustomSyncUpWithLocallyCreatedRecords() { val names = arrayOf(createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT), createRecordName(Constants.ACCOUNT)); createAccountsLocally(names); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.HARD_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE, true); val idToFieldsCreated = getIdToFieldsByName(ACCOUNTS_SOUP, arrayOf(Constants.NAME, Constants.DESCRIPTION), Constants.NAME, names); checkDbStateFlags(idToFieldsCreated.keys, true, false, false, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records created by target", 0, collector.createdRecordIds.size); idToFields.putAll(idToFieldsCreated) }
    @Test fun testSoftFailingCustomSyncUpWithLocallyDeletedRecords() { trySyncDown(MergeMode.OVERWRITE); val allIds = idToFields.keys.toTypedArray(); val idsLocallyDeleted = arrayOf(allIds[0], allIds[1], allIds[2]); deleteRecordsLocally(ACCOUNTS_SOUP, *idsLocallyDeleted); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.SOFT_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE); checkDbStateFlags(idsLocallyDeleted.toList(), false, false, true, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records created by target", 0, collector.deletedRecordIds.size) }
    @Test fun testHardFailingCustomSyncUpWithLocallyDeletedRecords() { trySyncDown(MergeMode.OVERWRITE); val allIds = idToFields.keys.toTypedArray(); val idsLocallyDeleted = arrayOf(allIds[0], allIds[1], allIds[2]); deleteRecordsLocally(ACCOUNTS_SOUP, *idsLocallyDeleted); val collector = TestSyncUpTarget.ActionCollector(); val target = TestSyncUpTarget(TestSyncUpTarget.SyncBehavior.HARD_FAIL_ON_SYNC); TestSyncUpTarget.setActionCollector(collector); trySyncUp(target, 3, MergeMode.OVERWRITE, true); checkDbStateFlags(idsLocallyDeleted.toList(), false, false, true, ACCOUNTS_SOUP); Assert.assertEquals("Wrong number of records created by target", 0, collector.deletedRecordIds.size) }
    @Test fun testCleanResyncGhostsForSOQLTarget() { val numberAccounts = 3; val accounts = createRecordsOnServer(numberAccounts, Constants.ACCOUNT); Assert.assertEquals("Wrong number of accounts created", numberAccounts, accounts.size); val accountIds = accounts.keys.toTypedArray(); val soql = "SELECT Id, Name FROM Account WHERE Id IN ${makeInClause(accountIds)}"; val syncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, SoqlSyncDownTarget(soql), ACCOUNTS_SOUP, accounts.size, 1, null); checkDbExist(ACCOUNTS_SOUP, accountIds, Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[0])), Constants.ACCOUNT); tryCleanResyncGhosts(syncId); checkDbExist(ACCOUNTS_SOUP, arrayOf(accountIds[1], accountIds[2]), Constants.ID); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[0]), Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[1], accountIds[2])), Constants.ACCOUNT) }
    @Test fun testCleanResyncGhostsWithMultipleSyncs() { val numberAccounts = 6; val accounts = createRecordsOnServer(numberAccounts, Constants.ACCOUNT); val accountIds = accounts.keys.toTypedArray(); val accountIdsFirstSubset = accountIds.copyOfRange(0, 3); val accountIdsSecondSubset = accountIds.copyOfRange(2, 6); val firstSyncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, SoqlSyncDownTarget("SELECT Id, Name FROM Account WHERE Id IN ${makeInClause(accountIdsFirstSubset)}"), ACCOUNTS_SOUP, accountIdsFirstSubset.size, 1, null); checkDbExist(ACCOUNTS_SOUP, accountIdsFirstSubset, Constants.ID); checkDbSyncIdField(accountIdsFirstSubset, firstSyncId, ACCOUNTS_SOUP); val secondSyncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, SoqlSyncDownTarget("SELECT Id, Name FROM Account WHERE Id IN ${makeInClause(accountIdsSecondSubset)}"), ACCOUNTS_SOUP, accountIdsSecondSubset.size, 1, null); checkDbExist(ACCOUNTS_SOUP, accountIdsSecondSubset, Constants.ID); checkDbSyncIdField(accountIdsSecondSubset, secondSyncId, ACCOUNTS_SOUP); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[0], accountIds[2], accountIds[5])), Constants.ACCOUNT); tryCleanResyncGhosts(firstSyncId); checkDbExist(ACCOUNTS_SOUP, arrayOf(accountIds[1], accountIds[2], accountIds[3], accountIds[4], accountIds[5]), Constants.ID); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[0]), Constants.ID); tryCleanResyncGhosts(secondSyncId); checkDbExist(ACCOUNTS_SOUP, arrayOf(accountIds[1], accountIds[3], accountIds[4]), Constants.ID); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[2], accountIds[5]), Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[1], accountIds[3], accountIds[4])), Constants.ACCOUNT) }
    @Test fun testCleanResyncGhostsForMRUTarget() { val numberAccounts = 3; val accounts = createRecordsOnServer(numberAccounts, Constants.ACCOUNT); val accountIds = accounts.keys.toTypedArray(); val fieldList = listOf(Constants.ID, Constants.NAME); val syncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, MruSyncDownTarget(fieldList, Constants.ACCOUNT), ACCOUNTS_SOUP); checkDbExist(ACCOUNTS_SOUP, accountIds, Constants.ID); deleteRecordsByIdOnServer(HashSet(singletonList(accountIds[0])), Constants.ACCOUNT); tryCleanResyncGhosts(syncId); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[0]), Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[1], accountIds[2])), Constants.ACCOUNT) }
    @Test fun testCleanResyncGhostsForSOSLTarget() { val accounts = createRecordsOnServer(1, Constants.ACCOUNT); Assert.assertEquals("1 account should have been created", 1, accounts.size); val accountIds = accounts.keys.toTypedArray(); val soslBuilder = SOSLBuilder.getInstanceWithSearchTerm(accounts[accountIds[0]]!!); val returningBuilder = SOSLReturningBuilder.getInstanceWithObjectName(Constants.ACCOUNT); returningBuilder.fields("Id, Name"); val sosl = soslBuilder.returning(returningBuilder).searchGroup("NAME FIELDS").build()!!; val syncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, SoslSyncDownTarget(sosl), ACCOUNTS_SOUP); checkDbExist(ACCOUNTS_SOUP, accountIds, Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[0])), Constants.ACCOUNT); tryCleanResyncGhosts(syncId); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[0]), Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[0])), Constants.ACCOUNT) }
    @Test fun testCreateGetDeleteSyncDownById() { val sync = SyncState.createSyncDown(smartStore, SoqlSyncDownTarget("SELECT Id, Name from Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, null); val syncId = sync.id; val fetchedSync = SyncState.byId(smartStore, syncId)!!; JSONTestHelper.assertSameJSON("Wrong sync state", sync.asJSON(), fetchedSync.asJSON()); SyncState.deleteSync(smartStore, syncId); Assert.assertNull("Sync should be gone", SyncState.byId(smartStore, syncId)) }
    @Test fun testCreateGetDeleteSyncDownWithName() { val syncName = "MyNamedSyncDown"; val sync = SyncState.createSyncDown(smartStore, SoqlSyncDownTarget("SELECT Id, Name from Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); val syncId = sync.id; val fetchedSync = SyncState.byName(smartStore, syncName)!!; JSONTestHelper.assertSameJSON("Wrong sync state", sync.asJSON(), fetchedSync.asJSON()); SyncState.deleteSync(smartStore, syncName); Assert.assertNull("Sync should be gone", SyncState.byId(smartStore, syncId)); Assert.assertNull("Sync should be gone", SyncState.byName(smartStore, syncName)) }
    @Test fun testCreateGetDeleteSyncUpById() { val sync = SyncState.createSyncUp(smartStore, SyncUpTarget(), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, null); val syncId = sync.id; val fetchedSync = SyncState.byId(smartStore, syncId)!!; JSONTestHelper.assertSameJSON("Wrong sync state", sync.asJSON(), fetchedSync.asJSON()); SyncState.deleteSync(smartStore, syncId); Assert.assertNull("Sync should be gone", SyncState.byId(smartStore, syncId)) }
    @Test fun testCreateGetDeleteSyncUpWithName() { val syncName = "MyNamedSyncUp"; val sync = SyncState.createSyncUp(smartStore, SyncUpTarget(), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); val syncId = sync.id; val fetchedSync = SyncState.byName(smartStore, syncName)!!; JSONTestHelper.assertSameJSON("Wrong sync state", sync.asJSON(), fetchedSync.asJSON()); SyncState.deleteSync(smartStore, syncName); Assert.assertNull("Sync should be gone", SyncState.byId(smartStore, syncId)); Assert.assertNull("Sync should be gone", SyncState.byName(smartStore, syncName)) }
    @Test fun testCreateSyncDownWithExistingName() { val syncName = "MyNamedSync"; SyncState.createSyncUp(smartStore, SyncUpTarget(), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); try { SyncState.createSyncDown(smartStore, SoqlSyncDownTarget("SELECT Id, Name from Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); Assert.fail("MobileSyncException should have been thrown") } catch (e: SyncManager.MobileSyncException) { Assert.assertTrue(e.message!!.contains("already a sync with name")) }; SyncState.deleteSync(smartStore, syncName); Assert.assertNull("Sync should be gone", SyncState.byName(smartStore, syncName)) }
    @Test fun testCreateSyncUpWithExistingName() { val syncName = "MyNamedSync"; SyncState.createSyncDown(smartStore, SoqlSyncDownTarget("SELECT Id, Name from Account"), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); try { SyncState.createSyncUp(smartStore, SyncUpTarget(), SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED), ACCOUNTS_SOUP, syncName); Assert.fail("MobileSyncException should have been thrown") } catch (e: SyncManager.MobileSyncException) { Assert.assertTrue(e.message!!.contains("already a sync with name")) }; SyncState.deleteSync(smartStore, syncName); Assert.assertNull("Sync should be gone", SyncState.byName(smartStore, syncName)) }
    @Test fun testCustomSyncDownTarget() { val syncName = "testCustomSyncDownTarget"; val numberOfRecords = 30; val target = TestSyncDownTarget("test", numberOfRecords, 10, 0); val syncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, target, ACCOUNTS_SOUP, numberOfRecords, 3, syncName); val sync = syncManager.getSyncStatus(syncId)!!; Assert.assertEquals("Wrong time stamp", target.dateForPosition(numberOfRecords - 1).time, sync.maxTimeStamp); checkDbForAfterTestSyncDown(target, ACCOUNTS_SOUP, numberOfRecords) }

    private fun checkDbForAfterTestSyncDown(target: TestSyncDownTarget, soupName: String, expectedNumberOfRecords: Int) { val query = QuerySpec.buildSmartQuerySpec(String.format("SELECT {%1\$s:%2\$s} from {%1\$s} where {%1\$s:%2\$s} like '%3\$s%%' order by {%1\$s:%2\$s}", soupName, Constants.ID, target.getIdPrefix()), Int.MAX_VALUE); val result = smartStore.query(query, 0); Assert.assertEquals("Wrong number of records", expectedNumberOfRecords, result.length()); for (i in 0 until expectedNumberOfRecords) { Assert.assertEquals("Wrong id", target.idForPosition(i), result.getJSONArray(i).getString(0)) } }
    private fun trySyncDown(mergeMode: MergeMode): Long = trySyncDown(mergeMode, null)
    private fun trySyncDown(mergeMode: MergeMode, syncName: String?): Long { val target = SoqlSyncDownTarget("SELECT Id, Name, Description, LastModifiedDate FROM Account WHERE Id IN ${makeInClause(idToFields.keys)}"); return trySyncDown(mergeMode, target, ACCOUNTS_SOUP, idToFields.size, 1, syncName) }

    class SlowSoqlSyncDownTarget : SoqlSyncDownTarget {
        constructor(query: String) : super(query) { this.queryType = QueryType.custom }
        constructor(target: JSONObject) : super(target)
        override fun startFetch(syncManager: SyncManager, maxTimeStamp: Long): JSONArray? { try { Thread.sleep(1000) } catch (e: InterruptedException) { }; return super.startFetch(syncManager, maxTimeStamp) }
    }

    @Test fun testReSyncRunningSync() { val target = SlowSoqlSyncDownTarget("SELECT Id, Name, LastModifiedDate FROM Account WHERE Id IN ${makeInClause(idToFields.keys)}"); val options = SyncOptions.optionsForSyncDown(MergeMode.LEAVE_IF_CHANGED); val sync = SyncState.createSyncDown(smartStore, target, options, ACCOUNTS_SOUP, null); val syncId = sync.id; checkStatus(sync, syncDown, syncId, target, options, NEW, 0, -1); val queue = SyncUpdateCallbackQueue(syncId); syncManager.runSync(sync, queue); queue.getNextSyncUpdate(syncId); try { syncManager.reSync(syncId, null); Assert.fail("Re sync should have failed") } catch (e: SyncManager.MobileSyncException) { Assert.assertTrue("Re sync should have failed because sync is already running", e.message!!.contains("still running")) }; while (!queue.getNextSyncUpdate(syncId).isDone) {}; try { Thread.sleep(1000) } catch (e: InterruptedException) { }; try { syncManager.reSync(syncId, queue) } catch (e: SyncManager.MobileSyncException) { Assert.fail("Re sync should not have failed") }; while (!queue.getNextSyncUpdate(syncId).isDone) {} }
    @Test fun testSyncCleanGhostsReSync() { val numberAccounts = 3; val accounts = createRecordsOnServer(numberAccounts, Constants.ACCOUNT); val accountIds = accounts.keys.toTypedArray(); val soql = "SELECT Id, Name FROM Account WHERE Id IN ${makeInClause(accountIds)}"; val syncId = trySyncDown(MergeMode.LEAVE_IF_CHANGED, SoqlSyncDownTarget(soql), ACCOUNTS_SOUP, accounts.size, 1, null); checkDbExist(ACCOUNTS_SOUP, accountIds, Constants.ID); deleteRecordsByIdOnServer(HashSet(listOf(accountIds[0])), Constants.ACCOUNT); tryCleanResyncGhosts(syncId); checkDbExist(ACCOUNTS_SOUP, arrayOf(accountIds[1], accountIds[2]), Constants.ID); checkDbDeleted(ACCOUNTS_SOUP, arrayOf(accountIds[0]), Constants.ID); val queue = SyncUpdateCallbackQueue(syncId); try { syncManager.reSync(syncId, queue) } catch (e: SyncManager.MobileSyncException) { Assert.fail("Unexpected exception:$e") }; while (!queue.getNextSyncUpdate(syncId).isDone) {}; deleteRecordsByIdOnServer(HashSet(listOf(accountIds[1], accountIds[2])), Constants.ACCOUNT) }
}
